// Code generated by MockGen. DO NOT EDIT.
// Source: shop_service.go
//
// Generated by this command:
//
//	mockgen -source=shop_service.go -destination=mock/mock_shop_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/elangreza/e-commerce/shop/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockShopRepo is a mock of ShopRepo interface.
type MockShopRepo struct {
	ctrl     *gomock.Controller
	recorder *MockShopRepoMockRecorder
	isgomock struct{}
}

// MockShopRepoMockRecorder is the mock recorder for MockShopRepo.
type MockShopRepoMockRecorder struct {
	mock *MockShopRepo
}

// NewMockShopRepo creates a new mock instance.
func NewMockShopRepo(ctrl *gomock.Controller) *MockShopRepo {
	mock := &MockShopRepo{ctrl: ctrl}
	mock.recorder = &MockShopRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShopRepo) EXPECT() *MockShopRepoMockRecorder {
	return m.recorder
}

// GetShopByIDs mocks base method.
func (m *MockShopRepo) GetShopByIDs(ctx context.Context, IDs ...int64) ([]entity.Shop, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range IDs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetShopByIDs", varargs...)
	ret0, _ := ret[0].([]entity.Shop)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShopByIDs indicates an expected call of GetShopByIDs.
func (mr *MockShopRepoMockRecorder) GetShopByIDs(ctx any, IDs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, IDs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShopByIDs", reflect.TypeOf((*MockShopRepo)(nil).GetShopByIDs), varargs...)
}
