// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/elangreza/e-commerce/gen (interfaces: WarehouseServiceClient)
//
// Generated by this command:
//
//	mockgen -package=mock -destination=mock/mock_deps.go github.com/elangreza/e-commerce/gen WarehouseServiceClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gen "github.com/elangreza/e-commerce/gen"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockWarehouseServiceClient is a mock of WarehouseServiceClient interface.
type MockWarehouseServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockWarehouseServiceClientMockRecorder
	isgomock struct{}
}

// MockWarehouseServiceClientMockRecorder is the mock recorder for MockWarehouseServiceClient.
type MockWarehouseServiceClientMockRecorder struct {
	mock *MockWarehouseServiceClient
}

// NewMockWarehouseServiceClient creates a new mock instance.
func NewMockWarehouseServiceClient(ctrl *gomock.Controller) *MockWarehouseServiceClient {
	mock := &MockWarehouseServiceClient{ctrl: ctrl}
	mock.recorder = &MockWarehouseServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWarehouseServiceClient) EXPECT() *MockWarehouseServiceClientMockRecorder {
	return m.recorder
}

// GetStocks mocks base method.
func (m *MockWarehouseServiceClient) GetStocks(ctx context.Context, in *gen.GetStockRequest, opts ...grpc.CallOption) (*gen.StockList, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStocks", varargs...)
	ret0, _ := ret[0].(*gen.StockList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStocks indicates an expected call of GetStocks.
func (mr *MockWarehouseServiceClientMockRecorder) GetStocks(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStocks", reflect.TypeOf((*MockWarehouseServiceClient)(nil).GetStocks), varargs...)
}

// GetWarehouseByShopID mocks base method.
func (m *MockWarehouseServiceClient) GetWarehouseByShopID(ctx context.Context, in *gen.GetWarehouseByShopIDRequest, opts ...grpc.CallOption) (*gen.GetWarehouseByShopIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetWarehouseByShopID", varargs...)
	ret0, _ := ret[0].(*gen.GetWarehouseByShopIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWarehouseByShopID indicates an expected call of GetWarehouseByShopID.
func (mr *MockWarehouseServiceClientMockRecorder) GetWarehouseByShopID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWarehouseByShopID", reflect.TypeOf((*MockWarehouseServiceClient)(nil).GetWarehouseByShopID), varargs...)
}

// ReleaseStock mocks base method.
func (m *MockWarehouseServiceClient) ReleaseStock(ctx context.Context, in *gen.ReleaseStockRequest, opts ...grpc.CallOption) (*gen.ReleaseStockResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReleaseStock", varargs...)
	ret0, _ := ret[0].(*gen.ReleaseStockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseStock indicates an expected call of ReleaseStock.
func (mr *MockWarehouseServiceClientMockRecorder) ReleaseStock(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseStock", reflect.TypeOf((*MockWarehouseServiceClient)(nil).ReleaseStock), varargs...)
}

// ReserveStock mocks base method.
func (m *MockWarehouseServiceClient) ReserveStock(ctx context.Context, in *gen.ReserveStockRequest, opts ...grpc.CallOption) (*gen.ReserveStockResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReserveStock", varargs...)
	ret0, _ := ret[0].(*gen.ReserveStockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReserveStock indicates an expected call of ReserveStock.
func (mr *MockWarehouseServiceClientMockRecorder) ReserveStock(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReserveStock", reflect.TypeOf((*MockWarehouseServiceClient)(nil).ReserveStock), varargs...)
}

// SetWarehouseStatus mocks base method.
func (m *MockWarehouseServiceClient) SetWarehouseStatus(ctx context.Context, in *gen.SetWarehouseStatusRequest, opts ...grpc.CallOption) (*gen.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetWarehouseStatus", varargs...)
	ret0, _ := ret[0].(*gen.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetWarehouseStatus indicates an expected call of SetWarehouseStatus.
func (mr *MockWarehouseServiceClientMockRecorder) SetWarehouseStatus(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWarehouseStatus", reflect.TypeOf((*MockWarehouseServiceClient)(nil).SetWarehouseStatus), varargs...)
}

// TransferStockBetweenWarehouse mocks base method.
func (m *MockWarehouseServiceClient) TransferStockBetweenWarehouse(ctx context.Context, in *gen.TransferStockBetweenWarehouseRequest, opts ...grpc.CallOption) (*gen.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TransferStockBetweenWarehouse", varargs...)
	ret0, _ := ret[0].(*gen.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransferStockBetweenWarehouse indicates an expected call of TransferStockBetweenWarehouse.
func (mr *MockWarehouseServiceClientMockRecorder) TransferStockBetweenWarehouse(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferStockBetweenWarehouse", reflect.TypeOf((*MockWarehouseServiceClient)(nil).TransferStockBetweenWarehouse), varargs...)
}
