// Code generated by MockGen. DO NOT EDIT.
// Source: order_service.go
//
// Generated by this command:
//
//	mockgen -source=order_service.go -destination=mock/mock_order_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	constanta "github.com/elangreza/e-commerce/order/internal/constanta"
	entity "github.com/elangreza/e-commerce/order/internal/entity"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockcartRepo is a mock of cartRepo interface.
type MockcartRepo struct {
	ctrl     *gomock.Controller
	recorder *MockcartRepoMockRecorder
	isgomock struct{}
}

// MockcartRepoMockRecorder is the mock recorder for MockcartRepo.
type MockcartRepoMockRecorder struct {
	mock *MockcartRepo
}

// NewMockcartRepo creates a new mock instance.
func NewMockcartRepo(ctrl *gomock.Controller) *MockcartRepo {
	mock := &MockcartRepo{ctrl: ctrl}
	mock.recorder = &MockcartRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcartRepo) EXPECT() *MockcartRepoMockRecorder {
	return m.recorder
}

// CreateCart mocks base method.
func (m *MockcartRepo) CreateCart(ctx context.Context, cart entity.Cart) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCart", ctx, cart)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCart indicates an expected call of CreateCart.
func (mr *MockcartRepoMockRecorder) CreateCart(ctx, cart any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCart", reflect.TypeOf((*MockcartRepo)(nil).CreateCart), ctx, cart)
}

// GetCartByUserID mocks base method.
func (m *MockcartRepo) GetCartByUserID(ctx context.Context, userID uuid.UUID) (*entity.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartByUserID", ctx, userID)
	ret0, _ := ret[0].(*entity.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartByUserID indicates an expected call of GetCartByUserID.
func (mr *MockcartRepoMockRecorder) GetCartByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartByUserID", reflect.TypeOf((*MockcartRepo)(nil).GetCartByUserID), ctx, userID)
}

// UpdateCartItem mocks base method.
func (m *MockcartRepo) UpdateCartItem(ctx context.Context, item entity.CartItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCartItem", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCartItem indicates an expected call of UpdateCartItem.
func (mr *MockcartRepoMockRecorder) UpdateCartItem(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCartItem", reflect.TypeOf((*MockcartRepo)(nil).UpdateCartItem), ctx, item)
}

// MockorderRepo is a mock of orderRepo interface.
type MockorderRepo struct {
	ctrl     *gomock.Controller
	recorder *MockorderRepoMockRecorder
	isgomock struct{}
}

// MockorderRepoMockRecorder is the mock recorder for MockorderRepo.
type MockorderRepoMockRecorder struct {
	mock *MockorderRepo
}

// NewMockorderRepo creates a new mock instance.
func NewMockorderRepo(ctrl *gomock.Controller) *MockorderRepo {
	mock := &MockorderRepo{ctrl: ctrl}
	mock.recorder = &MockorderRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockorderRepo) EXPECT() *MockorderRepoMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockorderRepo) CreateOrder(ctx context.Context, order entity.Order) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, order)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockorderRepoMockRecorder) CreateOrder(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockorderRepo)(nil).CreateOrder), ctx, order)
}

// GetExpiryOrders mocks base method.
func (m *MockorderRepo) GetExpiryOrders(ctx context.Context, duration time.Duration) ([]entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExpiryOrders", ctx, duration)
	ret0, _ := ret[0].([]entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExpiryOrders indicates an expected call of GetExpiryOrders.
func (mr *MockorderRepoMockRecorder) GetExpiryOrders(ctx, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExpiryOrders", reflect.TypeOf((*MockorderRepo)(nil).GetExpiryOrders), ctx, duration)
}

// GetOrderByID mocks base method.
func (m *MockorderRepo) GetOrderByID(ctx context.Context, orderID uuid.UUID) (*entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByID", ctx, orderID)
	ret0, _ := ret[0].(*entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByID indicates an expected call of GetOrderByID.
func (mr *MockorderRepoMockRecorder) GetOrderByID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByID", reflect.TypeOf((*MockorderRepo)(nil).GetOrderByID), ctx, orderID)
}

// GetOrderByIdempotencyKey mocks base method.
func (m *MockorderRepo) GetOrderByIdempotencyKey(ctx context.Context, idempotencyKey uuid.UUID) (*entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByIdempotencyKey", ctx, idempotencyKey)
	ret0, _ := ret[0].(*entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByIdempotencyKey indicates an expected call of GetOrderByIdempotencyKey.
func (mr *MockorderRepoMockRecorder) GetOrderByIdempotencyKey(ctx, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByIdempotencyKey", reflect.TypeOf((*MockorderRepo)(nil).GetOrderByIdempotencyKey), ctx, idempotencyKey)
}

// GetOrderByTransactionID mocks base method.
func (m *MockorderRepo) GetOrderByTransactionID(ctx context.Context, transactionID string) (*entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByTransactionID", ctx, transactionID)
	ret0, _ := ret[0].(*entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByTransactionID indicates an expected call of GetOrderByTransactionID.
func (mr *MockorderRepoMockRecorder) GetOrderByTransactionID(ctx, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByTransactionID", reflect.TypeOf((*MockorderRepo)(nil).GetOrderByTransactionID), ctx, transactionID)
}

// GetOrderList mocks base method.
func (m *MockorderRepo) GetOrderList(ctx context.Context, req entity.GetOrderListRequest) ([]entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderList", ctx, req)
	ret0, _ := ret[0].([]entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderList indicates an expected call of GetOrderList.
func (mr *MockorderRepoMockRecorder) GetOrderList(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderList", reflect.TypeOf((*MockorderRepo)(nil).GetOrderList), ctx, req)
}

// UpdateOrder mocks base method.
func (m *MockorderRepo) UpdateOrder(ctx context.Context, payloads map[string]any, orderID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrder", ctx, payloads, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrder indicates an expected call of UpdateOrder.
func (mr *MockorderRepoMockRecorder) UpdateOrder(ctx, payloads, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrder", reflect.TypeOf((*MockorderRepo)(nil).UpdateOrder), ctx, payloads, orderID)
}

// UpdateOrderStatusWithCallback mocks base method.
func (m *MockorderRepo) UpdateOrderStatusWithCallback(ctx context.Context, status constanta.OrderStatus, orderID uuid.UUID, callback func() error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatusWithCallback", ctx, status, orderID, callback)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderStatusWithCallback indicates an expected call of UpdateOrderStatusWithCallback.
func (mr *MockorderRepoMockRecorder) UpdateOrderStatusWithCallback(ctx, status, orderID, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatusWithCallback", reflect.TypeOf((*MockorderRepo)(nil).UpdateOrderStatusWithCallback), ctx, status, orderID, callback)
}
