// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/elangreza/e-commerce/gen (interfaces: OrderServiceClient)
//
// Generated by this command:
//
//	mockgen -package=mock -destination=mock/mock_deps.go github.com/elangreza/e-commerce/gen OrderServiceClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gen "github.com/elangreza/e-commerce/gen"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockOrderServiceClient is a mock of OrderServiceClient interface.
type MockOrderServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockOrderServiceClientMockRecorder
	isgomock struct{}
}

// MockOrderServiceClientMockRecorder is the mock recorder for MockOrderServiceClient.
type MockOrderServiceClientMockRecorder struct {
	mock *MockOrderServiceClient
}

// NewMockOrderServiceClient creates a new mock instance.
func NewMockOrderServiceClient(ctrl *gomock.Controller) *MockOrderServiceClient {
	mock := &MockOrderServiceClient{ctrl: ctrl}
	mock.recorder = &MockOrderServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderServiceClient) EXPECT() *MockOrderServiceClientMockRecorder {
	return m.recorder
}

// AddProductToCart mocks base method.
func (m *MockOrderServiceClient) AddProductToCart(ctx context.Context, in *gen.AddCartItemRequest, opts ...grpc.CallOption) (*gen.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddProductToCart", varargs...)
	ret0, _ := ret[0].(*gen.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddProductToCart indicates an expected call of AddProductToCart.
func (mr *MockOrderServiceClientMockRecorder) AddProductToCart(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProductToCart", reflect.TypeOf((*MockOrderServiceClient)(nil).AddProductToCart), varargs...)
}

// CallbackTransaction mocks base method.
func (m *MockOrderServiceClient) CallbackTransaction(ctx context.Context, in *gen.CallbackTransactionRequest, opts ...grpc.CallOption) (*gen.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CallbackTransaction", varargs...)
	ret0, _ := ret[0].(*gen.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CallbackTransaction indicates an expected call of CallbackTransaction.
func (mr *MockOrderServiceClientMockRecorder) CallbackTransaction(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallbackTransaction", reflect.TypeOf((*MockOrderServiceClient)(nil).CallbackTransaction), varargs...)
}

// CreateOrder mocks base method.
func (m *MockOrderServiceClient) CreateOrder(ctx context.Context, in *gen.CreateOrderRequest, opts ...grpc.CallOption) (*gen.Order, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateOrder", varargs...)
	ret0, _ := ret[0].(*gen.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockOrderServiceClientMockRecorder) CreateOrder(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockOrderServiceClient)(nil).CreateOrder), varargs...)
}

// GetCart mocks base method.
func (m *MockOrderServiceClient) GetCart(ctx context.Context, in *gen.Empty, opts ...grpc.CallOption) (*gen.Cart, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCart", varargs...)
	ret0, _ := ret[0].(*gen.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCart indicates an expected call of GetCart.
func (mr *MockOrderServiceClientMockRecorder) GetCart(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCart", reflect.TypeOf((*MockOrderServiceClient)(nil).GetCart), varargs...)
}

// GetOrder mocks base method.
func (m *MockOrderServiceClient) GetOrder(ctx context.Context, in *gen.GetOrderRequest, opts ...grpc.CallOption) (*gen.Order, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOrder", varargs...)
	ret0, _ := ret[0].(*gen.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockOrderServiceClientMockRecorder) GetOrder(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockOrderServiceClient)(nil).GetOrder), varargs...)
}

// GetOrderList mocks base method.
func (m *MockOrderServiceClient) GetOrderList(ctx context.Context, in *gen.GetOrderListRequest, opts ...grpc.CallOption) (*gen.Orders, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOrderList", varargs...)
	ret0, _ := ret[0].(*gen.Orders)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderList indicates an expected call of GetOrderList.
func (mr *MockOrderServiceClientMockRecorder) GetOrderList(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderList", reflect.TypeOf((*MockOrderServiceClient)(nil).GetOrderList), varargs...)
}
