// Code generated by MockGen. DO NOT EDIT.
// Source: payment_service.go
//
// Generated by this command:
//
//	mockgen -source=payment_service.go -destination=mock/mock_payment_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	constanta "github.com/elangreza/e-commerce/payment/internal/constanta"
	entity "github.com/elangreza/e-commerce/payment/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockpaymentRepo is a mock of paymentRepo interface.
type MockpaymentRepo struct {
	ctrl     *gomock.Controller
	recorder *MockpaymentRepoMockRecorder
	isgomock struct{}
}

// MockpaymentRepoMockRecorder is the mock recorder for MockpaymentRepo.
type MockpaymentRepoMockRecorder struct {
	mock *MockpaymentRepo
}

// NewMockpaymentRepo creates a new mock instance.
func NewMockpaymentRepo(ctrl *gomock.Controller) *MockpaymentRepo {
	mock := &MockpaymentRepo{ctrl: ctrl}
	mock.recorder = &MockpaymentRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpaymentRepo) EXPECT() *MockpaymentRepoMockRecorder {
	return m.recorder
}

// CreatePayment mocks base method.
func (m *MockpaymentRepo) CreatePayment(ctx context.Context, payment entity.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayment", ctx, payment)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePayment indicates an expected call of CreatePayment.
func (mr *MockpaymentRepoMockRecorder) CreatePayment(ctx, payment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayment", reflect.TypeOf((*MockpaymentRepo)(nil).CreatePayment), ctx, payment)
}

// GetExpiredPayments mocks base method.
func (m *MockpaymentRepo) GetExpiredPayments(ctx context.Context, duration time.Duration) ([]entity.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExpiredPayments", ctx, duration)
	ret0, _ := ret[0].([]entity.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExpiredPayments indicates an expected call of GetExpiredPayments.
func (mr *MockpaymentRepoMockRecorder) GetExpiredPayments(ctx, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExpiredPayments", reflect.TypeOf((*MockpaymentRepo)(nil).GetExpiredPayments), ctx, duration)
}

// GetPaymentByTransactionID mocks base method.
func (m *MockpaymentRepo) GetPaymentByTransactionID(ctx context.Context, transactionID string) (*entity.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentByTransactionID", ctx, transactionID)
	ret0, _ := ret[0].(*entity.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentByTransactionID indicates an expected call of GetPaymentByTransactionID.
func (mr *MockpaymentRepoMockRecorder) GetPaymentByTransactionID(ctx, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentByTransactionID", reflect.TypeOf((*MockpaymentRepo)(nil).GetPaymentByTransactionID), ctx, transactionID)
}

// UpdatePaymentStatusByTransactionID mocks base method.
func (m *MockpaymentRepo) UpdatePaymentStatusByTransactionID(ctx context.Context, paymentStatus constanta.PaymentStatus, transactionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePaymentStatusByTransactionID", ctx, paymentStatus, transactionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePaymentStatusByTransactionID indicates an expected call of UpdatePaymentStatusByTransactionID.
func (mr *MockpaymentRepoMockRecorder) UpdatePaymentStatusByTransactionID(ctx, paymentStatus, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePaymentStatusByTransactionID", reflect.TypeOf((*MockpaymentRepo)(nil).UpdatePaymentStatusByTransactionID), ctx, paymentStatus, transactionID)
}
