// Code generated by MockGen. DO NOT EDIT.
// Source: warehouse_service.go
//
// Generated by this command:
//
//	mockgen -source=warehouse_service.go -destination=mock/mock_warehouse_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/elangreza/e-commerce/warehouse/internal/entity"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockwarehouseRepo is a mock of warehouseRepo interface.
type MockwarehouseRepo struct {
	ctrl     *gomock.Controller
	recorder *MockwarehouseRepoMockRecorder
	isgomock struct{}
}

// MockwarehouseRepoMockRecorder is the mock recorder for MockwarehouseRepo.
type MockwarehouseRepoMockRecorder struct {
	mock *MockwarehouseRepo
}

// NewMockwarehouseRepo creates a new mock instance.
func NewMockwarehouseRepo(ctrl *gomock.Controller) *MockwarehouseRepo {
	mock := &MockwarehouseRepo{ctrl: ctrl}
	mock.recorder = &MockwarehouseRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockwarehouseRepo) EXPECT() *MockwarehouseRepoMockRecorder {
	return m.recorder
}

// GetStocks mocks base method.
func (m *MockwarehouseRepo) GetStocks(ctx context.Context, productIDs []string) ([]*entity.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStocks", ctx, productIDs)
	ret0, _ := ret[0].([]*entity.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStocks indicates an expected call of GetStocks.
func (mr *MockwarehouseRepoMockRecorder) GetStocks(ctx, productIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStocks", reflect.TypeOf((*MockwarehouseRepo)(nil).GetStocks), ctx, productIDs)
}

// GetWarehouseByIDs mocks base method.
func (m *MockwarehouseRepo) GetWarehouseByIDs(ctx context.Context, productID ...uuid.UUID) ([]entity.Warehouse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range productID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetWarehouseByIDs", varargs...)
	ret0, _ := ret[0].([]entity.Warehouse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWarehouseByIDs indicates an expected call of GetWarehouseByIDs.
func (mr *MockwarehouseRepoMockRecorder) GetWarehouseByIDs(ctx any, productID ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, productID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWarehouseByIDs", reflect.TypeOf((*MockwarehouseRepo)(nil).GetWarehouseByIDs), varargs...)
}

// GetWarehouseByShopID mocks base method.
func (m *MockwarehouseRepo) GetWarehouseByShopID(ctx context.Context, shopID int64) ([]entity.Warehouse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWarehouseByShopID", ctx, shopID)
	ret0, _ := ret[0].([]entity.Warehouse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWarehouseByShopID indicates an expected call of GetWarehouseByShopID.
func (mr *MockwarehouseRepoMockRecorder) GetWarehouseByShopID(ctx, shopID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWarehouseByShopID", reflect.TypeOf((*MockwarehouseRepo)(nil).GetWarehouseByShopID), ctx, shopID)
}

// ReleaseStock mocks base method.
func (m *MockwarehouseRepo) ReleaseStock(ctx context.Context, releaseStock entity.ReleaseStock) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseStock", ctx, releaseStock)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseStock indicates an expected call of ReleaseStock.
func (mr *MockwarehouseRepoMockRecorder) ReleaseStock(ctx, releaseStock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseStock", reflect.TypeOf((*MockwarehouseRepo)(nil).ReleaseStock), ctx, releaseStock)
}

// ReserveStock mocks base method.
func (m *MockwarehouseRepo) ReserveStock(ctx context.Context, reserveStock entity.ReserveStock) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReserveStock", ctx, reserveStock)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReserveStock indicates an expected call of ReserveStock.
func (mr *MockwarehouseRepoMockRecorder) ReserveStock(ctx, reserveStock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReserveStock", reflect.TypeOf((*MockwarehouseRepo)(nil).ReserveStock), ctx, reserveStock)
}

// SetWarehouseStatus mocks base method.
func (m *MockwarehouseRepo) SetWarehouseStatus(ctx context.Context, warehouseID int64, isActive bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWarehouseStatus", ctx, warehouseID, isActive)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWarehouseStatus indicates an expected call of SetWarehouseStatus.
func (mr *MockwarehouseRepoMockRecorder) SetWarehouseStatus(ctx, warehouseID, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWarehouseStatus", reflect.TypeOf((*MockwarehouseRepo)(nil).SetWarehouseStatus), ctx, warehouseID, isActive)
}

// TransferStockBetweenWarehouse mocks base method.
func (m *MockwarehouseRepo) TransferStockBetweenWarehouse(ctx context.Context, fromWarehouseID, toWarehouseID int64, productID string, quantity int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferStockBetweenWarehouse", ctx, fromWarehouseID, toWarehouseID, productID, quantity)
	ret0, _ := ret[0].(error)
	return ret0
}

// TransferStockBetweenWarehouse indicates an expected call of TransferStockBetweenWarehouse.
func (mr *MockwarehouseRepoMockRecorder) TransferStockBetweenWarehouse(ctx, fromWarehouseID, toWarehouseID, productID, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferStockBetweenWarehouse", reflect.TypeOf((*MockwarehouseRepo)(nil).TransferStockBetweenWarehouse), ctx, fromWarehouseID, toWarehouseID, productID, quantity)
}
